apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
  {{- include "backend.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.backend.selectorName  }}
  type: ClusterIP