apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
  {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.selectorName  }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.backend.selectorName  }}
          image: {{ .Values.backend.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.backend.container.containerPort }}
              protocol: TCP
          resources:
           {{- toYaml .Values.app.computerc | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
