apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.selectorName  }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.frontend.selectorName  }}
          image: {{ .Values.frontend.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.frontend.container.containerPort }}
              protocol: TCP
          env:
          - name: API_BASE_URL
            value: {{ .Values.frontend.container.baseURL }}
          resources:
           {{- toYaml .Values.app.computerc | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http