frontend:
  container:
    image: joyce237/fueled-frontend
    containerPort: 3000
    baseURL: "http://backend-service.stage.svc.cluster.local:8080"

backend:
  container:
    image: joyce237/fueled-test-backend
    containerPort: 8080

app:
  replicas: 1
  env: stage
  computerc:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

hpa:
  enabled: false
